# Generated by Django 5.2.13 on 2026-04-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_gallery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='Free Wi-fi,AC,Smart TV', null=True),
        ),
    ]
