# Generated by Django 5.2.13 on 2026-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_inventory',
            field=models.IntegerField(default=5, help_text='এই টাইপের মোট কতগুলো রুম হোটেলে আছে'),
        ),
    ]
