# Generated by Django 5.2.13 on 2026-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_room_total_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='total_inventory',
            field=models.IntegerField(default=5, help_text='Total number of rooms of this type available in the hotel'),
        ),
    ]
